<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entities\OutboxMessages\Readers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Atlas.SharedKernel\Atlas.SharedKernel.csproj" />
    <ProjectReference Include="..\Atlas.BuildingBlocks.Audit\Atlas.BuildingBlocks.Audit.csproj" />
  </ItemGroup>

</Project>
