<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.1.0" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Atlas.BuildingBlocks.AspNetCore\Atlas.BuildingBlocks.AspNetCore.csproj" />
    <ProjectReference Include="..\..\Atlas.BuildingBlocks.AuditTrail\Atlas.BuildingBlocks.Audit.csproj" />
    <ProjectReference Include="..\..\Atlas.BuildingBlocks.FastEndpoints\Atlas.BuildingBlocks.FastEndpoints.csproj" />
    <ProjectReference Include="..\Atlas.Staff.Application\Atlas.Staff.Application.csproj" />
    <ProjectReference Include="..\Atlas.Staff.Contracts\Atlas.Staff.Contracts.csproj" />
    <ProjectReference Include="..\Atlas.Staff.Domain\Atlas.Staff.Domain.csproj" />
    <ProjectReference Include="..\Atlas.Staff.Resources\Atlas.Staff.Resources.csproj" />
  </ItemGroup>

</Project>
