info:
  name: Roles-Lookup
  type: http
  seq: 2

http:
  method: GET
  url: "{{bff_api_prefix}}/bff/v1/identity/roles/lookup"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
