info:
  name: Roles-GetById
  type: http
  seq: 6

http:
  method: get
  url: "{{bff_api_prefix}}/bff/v1/identity/roles/00000000-0000-0000-0000-000000000002"
  auth: inherit

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
