<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Abstractions\Tenants\**" />
    <EmbeddedResource Remove="Abstractions\Tenants\**" />
    <None Remove="Abstractions\Tenants\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atlas.BuildingBlocks.Email\Atlas.BuildingBlocks.Email.csproj" />
    <ProjectReference Include="..\Atlas.BuildingBlocks.Infrastructure\Atlas.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\Atlas.Contracts\Atlas.Integration.Contracts.csproj" />
    <ProjectReference Include="..\Atlas.Identity.Domain\Atlas.Identity.Domain.csproj" />
    <ProjectReference Include="..\Atlas.SharedKernel\Atlas.SharedKernel.csproj" />
  </ItemGroup>

</Project>
