
namespace Atlas.API.Security.Headers;

/// <summary>
/// Adds a baseline set of HTTP security headers to all responses generated by the BFF.
/// 
/// Security Rules:
/// #1 Prevents clickjacking via X-Frame-Options and CSP frame-ancestors.
/// #2 Disables MIME type sniffing via X-Content-Type-Options.
/// #3 Restricts referrer leakage via Referrer-Policy.
/// #4 Applies strict no-store cache policy for authenticated responses.
/// #5 Enforces a restrictive Content Security Policy (default-src 'self').
/// #6 Restricts browser feature access via Permissions-Policy.
/// 
/// Cache-Control is applied only for authenticated requests to avoid
/// caching sensitive data while allowing public responses to remain cacheable.
/// 
/// This middleware centralizes security behavior and keeps Program.cs clean.
/// </summary>


public static class SecurityHeadersExtensions
{
    public static IApplicationBuilder UseSecurityHeaders(this IApplicationBuilder app)
    {
        return app.Use(async (ctx, next) =>
        {
            var env = ctx.RequestServices
                .GetRequiredService<IWebHostEnvironment>();

            var h = ctx.Response.Headers;

            // #1 Clickjacking
            h["X-Frame-Options"] = "DENY";

            if (env.IsDevelopment())
            {
                // 🔓 Relaxed CSP for DEV (Scalar + Browser refresh)
                h["Content-Security-Policy"] =
                    "default-src 'self'; " +
                    "script-src 'self' 'unsafe-inline'; " +
                    "style-src 'self' 'unsafe-inline'; " +
                    "font-src 'self' data:; " +
                    "connect-src 'self' ws: wss:; " +
                    "frame-ancestors 'none';";
            }
            else
            {
                // 🔐 Strict CSP for PROD
                h["Content-Security-Policy"] =
                    "default-src 'self'; " +
                    "frame-ancestors 'none';";
            }

            h["X-Content-Type-Options"] = "nosniff";
            h["Referrer-Policy"] = "strict-origin-when-cross-origin";
            h["Permissions-Policy"] =
                "camera=(), microphone=(), geolocation=(), payment=()";

            if (ctx.User.Identity?.IsAuthenticated == true)
            {
                h["Cache-Control"] = "no-store, no-cache, must-revalidate";
                h["Pragma"] = "no-cache";
                h["Expires"] = "0";
            }

            await next();
        });
    }
}
