
namespace Atlas.API.Security.Headers;

/// <summary>
/// Adds a baseline set of HTTP security headers to all responses generated by the BFF.
/// 
/// Security Rules:
/// #1 Prevents clickjacking via X-Frame-Options and CSP frame-ancestors.
/// #2 Disables MIME type sniffing via X-Content-Type-Options.
/// #3 Restricts referrer leakage via Referrer-Policy.
/// #4 Applies strict no-store cache policy for authenticated responses.
/// #5 Enforces a restrictive Content Security Policy (default-src 'self').
/// #6 Restricts browser feature access via Permissions-Policy.
/// 
/// Cache-Control is applied only for authenticated requests to avoid
/// caching sensitive data while allowing public responses to remain cacheable.
/// 
/// This middleware centralizes security behavior and keeps Program.cs clean.
/// </summary>


public static class SecurityHeadersExtensions
{
    public static IApplicationBuilder UseSecurityHeaders(this IApplicationBuilder app)
    {
        return app.Use(async (ctx, next) =>
        {
            var h = ctx.Response.Headers;

            // #1 Prevent clickjacking
            h["X-Frame-Options"] = "DENY";
            h["Content-Security-Policy"] = "default-src 'self'; frame-ancestors 'none';";
            //h["Content-Security-Policy"] =
            //    "default-src 'self'; " +
            //    "script-src 'self'; " +
            //    "style-src 'self'; " +
            //    "img-src 'self' data:; " +
            //    "connect-src 'self' https://login.microsoftonline.com; " +
            //    "frame-ancestors 'none';";

            // #2 Prevent MIME sniffing
            h["X-Content-Type-Options"] = "nosniff";

            // #3 Restrict referrer leakage
            h["Referrer-Policy"] = "strict-origin-when-cross-origin";

            // #6 Restrict browser features
            h["Permissions-Policy"] = "camera=(), microphone=(), geolocation=(), payment=()";

            // #4 Prevent caching of authenticated responses
            if (ctx.User.Identity?.IsAuthenticated == true)
            {
                h["Cache-Control"] = "no-store, no-cache, must-revalidate";
                h["Pragma"] = "no-cache";
                h["Expires"] = "0";
            }

            await next();
        });
    }
}
