<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Atlas.BuildingBlocks.AspNetCore\Atlas.BuildingBlocks.AspNetCore.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Atlas.BuildingBlocks.Audit\Atlas.BuildingBlocks.Audit.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Atlas.BuildingBlocks.FastEndpoints\Atlas.BuildingBlocks.FastEndpoints.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Atlas.BuildingBlocks.Permissions\Atlas.BuildingBlocks.Permissions.csproj" />
    <ProjectReference Include="..\..\Shared\Atlas.SharedKernel\Atlas.SharedKernel.csproj" />
    <ProjectReference Include="..\Atlas.Party.Contracts\Atlas.Party.Contracts.csproj" />
    <ProjectReference Include="..\Atlas.Party.Application\Atlas.Party.Application.csproj" />
    <ProjectReference Include="..\Atlas.Party.Domain\Atlas.Party.Domain.csproj" />
    <ProjectReference Include="..\Atlas.Party.Resources\Atlas.Party.Resources.csproj" />
  </ItemGroup>

</Project>
