// <auto-generated />
using System;
using Atlas.Party.Infrastructure.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atlas.Party.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PartyDbContext))]
    partial class PartyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("atlas_party")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atlas.BuildingBlocks.Persistence.Entities.Audits.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes_json");

                    b.Property<string>("EntityId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("EntityTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_type_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audits");

                    b.HasIndex("EntityTypeId")
                        .HasDatabaseName("ix_audits_entity_type_id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audits_occurred_at_utc");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_audits_tenant_id");

                    b.HasIndex("TenantId", "EntityTypeId", "EntityId")
                        .HasDatabaseName("ix_audits_tenant_id_entity_type_id_entity_id");

                    b.HasIndex("TenantId", "EntityTypeId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audits_tenant_id_entity_type_id_occurred_at_utc");

                    b.HasIndex("TenantId", "EntityTypeId", "Action", "OccurredAtUtc")
                        .HasDatabaseName("ix_audits_tenant_id_entity_type_id_action_occurred_at_utc");

                    b.ToTable("audits", "atlas_party");
                });

            modelBuilder.Entity("Atlas.BuildingBlocks.Persistence.Entities.Idempotency.IdempotencyEntry", b =>
                {
                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("HandlerName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("handler_name");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("IdempotencyKey", "HandlerName")
                        .HasName("pk_idempotency_entries");

                    b.ToTable("idempotency_entries", "atlas_party");
                });

            modelBuilder.Entity("Atlas.Party.Domain.Parties.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by_email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("tax_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("UpdatedByEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by_email");

                    b.Property<string>("party_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("party_type");

                    b.HasKey("Id")
                        .HasName("pk_parties");

                    b.HasIndex("TenantId", "TaxNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_parties_tenant_id_tax_number");

                    b.ToTable("parties", "atlas_party");

                    b.HasDiscriminator<string>("party_type").HasValue("Party");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Atlas.SharedKernel.Application.OutboxMessages.OutboxHandlerExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("HandlerName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("handler_name");

                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_outbox_handler_executions");

                    b.HasIndex("AttemptedAt")
                        .HasDatabaseName("ix_outbox_handler_executions_attempted_at");

                    b.HasIndex("OutboxMessageId")
                        .HasDatabaseName("ix_outbox_handler_executions_outbox_message_id");

                    b.HasIndex("HandlerName", "Status")
                        .HasDatabaseName("ix_outbox_handler_executions_handler_name_status");

                    b.ToTable("outbox_handler_executions", "atlas_party");
                });

            modelBuilder.Entity("Atlas.SharedKernel.Application.OutboxMessages.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("attempt_number");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime?>("DeadLetteredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_on");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Automatic")
                        .HasColumnName("origin");

                    b.Property<Guid?>("ParentOutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_outbox_message_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on");

                    b.Property<string>("ResubmittedByEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("resubmitted_by_email");

                    b.Property<Guid?>("ResubmittedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resubmitted_by_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("type");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("user_email");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("IdempotencyKey")
                        .HasDatabaseName("ix_outbox_messages_idempotency_key");

                    b.HasIndex("Module")
                        .HasDatabaseName("ix_outbox_messages_module");

                    b.HasIndex("ParentOutboxMessageId")
                        .HasDatabaseName("ix_outbox_messages_parent_outbox_message_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_outbox_messages_tenant_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_outbox_messages_type");

                    b.HasIndex("ProcessedOn", "DeadLetteredOn", "FailedAt", "LockedUntil", "OccurredOn")
                        .HasDatabaseName("ix_outbox_messages_processed_on_dead_lettered_on_failed_at_loc");

                    b.ToTable("outbox_messages", "atlas_party");
                });

            modelBuilder.Entity("Atlas.Party.Domain.Parties.Organization", b =>
                {
                    b.HasBaseType("Atlas.Party.Domain.Parties.Party");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("LegalType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("legal_type");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trade_name");

                    b.HasDiscriminator().HasValue("Organization");
                });

            modelBuilder.Entity("Atlas.Party.Domain.Parties.Person", b =>
                {
                    b.HasBaseType("Atlas.Party.Domain.Parties.Party");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.HasDiscriminator().HasValue("Person");
                });

            modelBuilder.Entity("Atlas.Party.Domain.Parties.Party", b =>
                {
                    b.OwnsMany("Atlas.Party.Domain.Parties.Address", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid?>("CreatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by");

                            b1.Property<string>("CreatedByEmail")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("created_by_email");

                            b1.Property<bool>("IsPrimary")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_primary");

                            b1.Property<Guid>("PartyId")
                                .HasColumnType("uuid")
                                .HasColumnName("party_id");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("type");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("updated_by");

                            b1.Property<string>("UpdatedByEmail")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("updated_by_email");

                            b1.HasKey("Id")
                                .HasName("pk_party_addresses");

                            b1.HasIndex("PartyId")
                                .HasDatabaseName("ix_party_addresses_party_id");

                            b1.ToTable("party_addresses", "atlas_party");

                            b1.WithOwner()
                                .HasForeignKey("PartyId")
                                .HasConstraintName("fk_party_addresses_parties_party_id");

                            b1.OwnsOne("Atlas.Party.Domain.Shared.PostalAddress", "PostalAddress", b2 =>
                                {
                                    b2.Property<Guid>("AddressId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("city");

                                    b2.Property<string>("Complement")
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("complement");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("character varying(2)")
                                        .HasColumnName("country");

                                    b2.Property<string>("District")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("district");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("number");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasMaxLength(2)
                                        .HasColumnType("character varying(2)")
                                        .HasColumnName("state");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("street");

                                    b2.Property<string>("ZipCode")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("zip_code");

                                    b2.HasKey("AddressId");

                                    b2.ToTable("party_addresses", "atlas_party");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressId")
                                        .HasConstraintName("fk_party_addresses_party_addresses_id");
                                });

                            b1.Navigation("PostalAddress")
                                .IsRequired();
                        });

                    b.OwnsMany("Atlas.Party.Domain.Parties.ContactInfo", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid?>("CreatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by");

                            b1.Property<string>("CreatedByEmail")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("created_by_email");

                            b1.Property<string>("Email")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("email");

                            b1.Property<bool>("IsPrimary")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_primary");

                            b1.Property<Guid>("PartyId")
                                .HasColumnType("uuid")
                                .HasColumnName("party_id");

                            b1.Property<string>("Phone")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("phone");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("type");

                            b1.Property<DateTime?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<Guid?>("UpdatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("updated_by");

                            b1.Property<string>("UpdatedByEmail")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("updated_by_email");

                            b1.HasKey("Id")
                                .HasName("pk_party_contacts");

                            b1.HasIndex("PartyId")
                                .HasDatabaseName("ix_party_contacts_party_id");

                            b1.ToTable("party_contacts", "atlas_party");

                            b1.WithOwner()
                                .HasForeignKey("PartyId")
                                .HasConstraintName("fk_party_contacts_parties_party_id");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("Atlas.SharedKernel.Application.OutboxMessages.OutboxHandlerExecution", b =>
                {
                    b.HasOne("Atlas.SharedKernel.Application.OutboxMessages.OutboxMessage", null)
                        .WithMany()
                        .HasForeignKey("OutboxMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_outbox_handler_executions_outbox_messages_outbox_message_id");
                });

            modelBuilder.Entity("Atlas.SharedKernel.Application.OutboxMessages.OutboxMessage", b =>
                {
                    b.HasOne("Atlas.SharedKernel.Application.OutboxMessages.OutboxMessage", null)
                        .WithMany()
                        .HasForeignKey("ParentOutboxMessageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_outbox_messages_outbox_messages_parent_outbox_message_id");
                });

            modelBuilder.Entity("Atlas.Party.Domain.Parties.Person", b =>
                {
                    b.OwnsOne("Atlas.Party.Domain.Shared.PersonName", "Name", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("middle_name");

                            b1.HasKey("PersonId");

                            b1.ToTable("parties", "atlas_party");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_persons_persons_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
