services:

  postgres:
    ports:
      - "5432:5432"

  # api:
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Development
  #     ConnectionStrings__Default: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
  #   ports:
  #     - "5000:8080"

  pgadmin:
    image: dpage/pgadmin4
    container_name: atlas-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - atlas-network
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json