<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atlas.BuildingBlocks.Infrastructure\Atlas.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\Atlas.Outbox.Contracts\Atlas.Outbox.Contracts.csproj" />
    <ProjectReference Include="..\Atlas.SharedKernel\Atlas.SharedKernel.csproj" />
  </ItemGroup>

</Project>
