<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Atlas.BuildingBlocks.Outbox\Atlas.BuildingBlocks.Outbox.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Atlas.BuildingBlocks.Persistence\Atlas.BuildingBlocks.Persistence.csproj" />
    <ProjectReference Include="..\..\Identity\Atlas.Identity.Infrastructure\Atlas.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Staff\Atlas.Staff.Infrastructure\Atlas.Staff.Infrastructure.csproj" />
    <ProjectReference Include="..\Atlas.Outbox.Application\Atlas.Outbox.Application.csproj" />
    <ProjectReference Include="..\Atlas.Outbox.Catalog\Atlas.Outbox.Catalog.csproj" />
  </ItemGroup>

</Project>
