### Create Staff
POST https://localhost:7106/api/staff
Content-Type: application/json

{
  "tenantId": "a9bc089b-9b88-40bd-88ce-4aa97424c5a6",
  "UserId": "12222222-2222-2222-2222-222222222222",
  "firstName": "João1",
  "lastName": "Silva1",
  "role": "Operator"
}