<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <!-- OpenTelemetry core + exporter -->
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />

    <!-- Instrumentation common to all hosts -->
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Process" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />

    <!-- Serilog OTLP sink + enrichers -->
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.OpenTelemetry" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
    <PackageReference Include="Serilog.Enrichers.Activity" />
  </ItemGroup>

</Project>
